[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "https://www.apotheek-dashboard.netlify.app/*"
  to = "https://apotheek-dashboard.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/calls"
  to = "/.netlify/functions/calls"
  status = 200

[dev]
  port = 8888
  autoLaunch = false
